import type { SearchMeta } from "@/lib/api";

/** Full US state list — used when /search/meta hasn't loaded yet or fails. */
const US_STATES: Array<{ code: string; name: string }> = [
  { code: "AL", name: "Alabama" },
  { code: "AK", name: "Alaska" },
  { code: "AZ", name: "Arizona" },
  { code: "AR", name: "Arkansas" },
  { code: "CA", name: "California" },
  { code: "CO", name: "Colorado" },
  { code: "CT", name: "Connecticut" },
  { code: "DE", name: "Delaware" },
  { code: "FL", name: "Florida" },
  { code: "GA", name: "Georgia" },
  { code: "HI", name: "Hawaii" },
  { code: "ID", name: "Idaho" },
  { code: "IL", name: "Illinois" },
  { code: "IN", name: "Indiana" },
  { code: "IA", name: "Iowa" },
  { code: "KS", name: "Kansas" },
  { code: "KY", name: "Kentucky" },
  { code: "LA", name: "Louisiana" },
  { code: "ME", name: "Maine" },
  { code: "MD", name: "Maryland" },
  { code: "MA", name: "Massachusetts" },
  { code: "MI", name: "Michigan" },
  { code: "MN", name: "Minnesota" },
  { code: "MS", name: "Mississippi" },
  { code: "MO", name: "Missouri" },
  { code: "MT", name: "Montana" },
  { code: "NE", name: "Nebraska" },
  { code: "NV", name: "Nevada" },
  { code: "NH", name: "New Hampshire" },
  { code: "NJ", name: "New Jersey" },
  { code: "NM", name: "New Mexico" },
  { code: "NY", name: "New York" },
  { code: "NC", name: "North Carolina" },
  { code: "ND", name: "North Dakota" },
  { code: "OH", name: "Ohio" },
  { code: "OK", name: "Oklahoma" },
  { code: "OR", name: "Oregon" },
  { code: "PA", name: "Pennsylvania" },
  { code: "RI", name: "Rhode Island" },
  { code: "SC", name: "South Carolina" },
  { code: "SD", name: "South Dakota" },
  { code: "TN", name: "Tennessee" },
  { code: "TX", name: "Texas" },
  { code: "UT", name: "Utah" },
  { code: "VT", name: "Vermont" },
  { code: "VA", name: "Virginia" },
  { code: "WA", name: "Washington" },
  { code: "WV", name: "West Virginia" },
  { code: "WI", name: "Wisconsin" },
  { code: "WY", name: "Wyoming" },
  { code: "DC", name: "District of Columbia" },
];

/** Canonical filter catalogs so dropdowns never collapse to only "Any". */
export const SEARCH_META_FALLBACK: SearchMeta = {
  states: ["Any", ...US_STATES.map((s) => `${s.code} — ${s.name}`)],
  state_codes: ["Any", ...US_STATES.map((s) => s.code)],
  regions: ["Any"],
  regions_by_state: { Any: ["Any"] },
  strategies: [
    "Any",
    "FARMLAND",
    "DEVELOPMENT",
    "LAND_BANK",
    "RECREATIONAL",
    "ENERGY",
    "TIMBER",
    "IMPROVED_PROPERTY",
    "CUSTOM",
  ],
  hold_years: ["Any", 1, 3, 5, 10, 15, 25, 40, 60, 80, 100],
  inventory_count: 0,
  inventory_states: [],
  inventory_by_state: {},
  attom: { configured: false, state: "PENDING", ok: false },
  price_presets: [
    { label: "Any", min: null, max: null },
    { label: "Up to $10k", min: null, max: 10000 },
    { label: "Up to $25k", min: null, max: 25000 },
    { label: "Up to $50k", min: null, max: 50000 },
    { label: "Up to $100k", min: null, max: 100000 },
    { label: "Up to $150k", min: null, max: 150000 },
    { label: "Up to $250k", min: null, max: 250000 },
    { label: "Up to $500k", min: null, max: 500000 },
    { label: "Up to $750k", min: null, max: 750000 },
    { label: "Up to $1M", min: null, max: 1000000 },
    { label: "Up to $2.5M", min: null, max: 2500000 },
    { label: "Up to $5M", min: null, max: 5000000 },
    { label: "$5M+", min: 5000000, max: null },
    { label: "Custom…", min: null, max: null },
  ],
  acre_presets: [
    { label: "Any", min: null, max: null },
    { label: "1+ ac", min: 1, max: null },
    { label: "5+ ac", min: 5, max: null },
    { label: "10+ ac", min: 10, max: null },
    { label: "20+ ac", min: 20, max: null },
    { label: "40+ ac", min: 40, max: null },
    { label: "80+ ac", min: 80, max: null },
    { label: "160+ ac", min: 160, max: null },
    { label: "320+ ac", min: 320, max: null },
    { label: "640+ ac", min: 640, max: null },
    { label: "Custom range…", min: null, max: null },
  ],
  sort_options: [
    { value: "fit_desc", label: "Best match for my filters" },
    { value: "score_desc", label: "Highest opportunity score (0–100)" },
    { value: "risk_asc", label: "Lowest risk score first" },
    { value: "confidence_desc", label: "Most complete files first" },
    { value: "price_asc", label: "Lowest price / starting bid" },
    { value: "price_desc", label: "Highest price / starting bid" },
    { value: "acres_desc", label: "Largest acreage first" },
    { value: "discount_asc", label: "Biggest gap under our estimated value" },
  ],
};
